### ISSUE TITLE
Add arrows buttons in unfolded textzone to bind arrow keys

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory#105]

**Comment by RouxRC** [comment]
could also apply to amendments now that keys are active :)

**Comment by njoyard** [comment]
Yes, I was thinking about that, too.

**Comment by njoyard** [comment]
Now the question is: what ordering should arrow buttons follow in the textzone ?

Now that we have snake-ordering back, left/right arrow keys don't match with the actual amendment order. But I think in unfolded textzone, navigation buttons should follow the amendment order no matter how they are displayed. What do you think ?

**Comment by boogheta** [comment]
I agree, when we see the viz, arrow keys have to follow the visual marker, but whenever we're unfolded, the most logical would be to follow the amendment sorting order (so when we'll have the discussion order choosable, we will eb able to do as eliasse and pass from the currently discussed to the next)

**Comment by njoyard** [comment]
Added pgup/pgdown to follow sorting order, and when in read mode left/up behave as pgup, and right/down as pgdown. See https://github.com/regardscitoyens/the-law-factory/commit/e0668eea8a69ab9e3267b483229af63dc57caa44.

**Comment by njoyard** [comment]
Added amendements navlinks in read mode (f5ec6a5)
