### ISSUE TITLE
le lien git ne marche pas

### ISSUE THREAD

**Issue by slim** [regardscitoyens/the-law-factory#125]
Quand tu choisis une loi dans l'explorateur des lois

http://www.lafabriquedelaloi.fr/lois.html

Quand tu cliques sur une loi, tu es présenté avec une fiche de loi contenant un lien git (entre autres)
Par exemple le lien git pour la loi "Contrefaçon" 

http://git.lafabriquedelaloi.fr/parlement/ppl12-866/

ce lien ne marche pas. Message du serveur :

500

We're sorry, but something went wrong.

Please contact your GitLab administrator if this problem persists.

**Comment by RouxRC** [comment]
Cette partie reposait sur gitlab dont le server était apparemment tombé, on l'a rallumé merci du ping!
