### ISSUE TITLE
Improve amendements display when loading

### ISSUE THREAD

**Issue by njoyard** [regardscitoyens/the-law-factory#132]
Ensure that no {{ }} angular interpolation is visible, that all containers are already the right size and show a spinner while first loading amendments

**Comment by RouxRC** [comment]
Different spinner but similar so saying it here: it still looks to me like the spinner in the sidebar appears on top of the previous selected amendment's text

**Comment by njoyard** [comment]
Yeah, that's because the spinner appears immediately, while current amendment fades out. I'll look what I can do.

**Comment by njoyard** [comment]
@RouxRC is that better for you?

**Comment by RouxRC** [comment]
yep, except for the spinner that eats the stepsbar as well, but should be handled after #152
