### ISSUE TITLE
Selection in amendment list is difficult

### ISSUE THREAD

**Issue by lpouget** [regardscitoyens/the-law-factory#134]
Hi,

On page : https://www.lafabriquedelaloi.fr/amendements.html?loi=pjl15-republique_numerique&etape=02_1%C3%A8relecture_assemblee_hemicycle

If you select a item in list, the unselection is not really intuitive. You must click outside item on the white panel only. User could expect that a click on grey border make the same thing.

And usually a new click on a selected item make a select all op.

Regards

**Comment by njoyard** [comment]
Hi,

Two questions to understand the issue better:
* are you talking about article selection or amendment selection ?
* which grey border are you talking about ? the outer border of the app ?

As far as articles are concerned, clicking anywhere outside the article in the article list unselects it, while clicking outside the list does not affect it. This seems pretty consistent (to me !) with usual deselection principles. As for amendments, you cannot unselect them.

Thanks for the feedback.

**Comment by fmassot** [comment]
I think it's about article selection which highlights amendements of the selected article.

As @lpouget said it, I agree that we can expect three behaviours : 
* when you click on the article, it should highlight its amendements. This one works :)
* when article's amendements are still highlighted, any click outside the article's title in the article list should unselect it, this one is already implemented ! @lpouget suggested to extend the "unselect" click from the article list to something wider but this will cause some problems : for exemple you will unselect the amendements if you miss a click on the legend for exemple. So for the moment I will keep the current implementation
* finally when article's amendements are still highlighted, if you click a second time on the article, it should cancel highlight.

**Comment by lpouget** [comment]
Effectively, @fmassot has resumed my thought. 

For me 3rd point should be a nice add because actually unselection is not really intuitive.
If @fmassot didn't tell me, I would not see it.

**Comment by RouxRC** [comment]
Hi all,

I feel like part of the problems comes from the fact that the whole line of a subject title is clickable, whereas one thinks he can click on all that white as for the regular background to unselect anything.
I think reducing the click to just the text of the title would help a lot

**Comment by njoyard** [comment]
Fixed by https://github.com/regardscitoyens/the-law-factory/commit/4e31910a108c90e1ff1630cba4ece732e034f612
