### ISSUE TITLE
Add DEBUG mode to config to silent api logs in prod

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory#140]

**Comment by fmassot** [comment]
actually, I put an example here to use in production : https://github.com/regardscitoyens/the-law-factory/blob/refactor-v2/public/js/config.js.example

the `$logProvider.debugEnabled(false);` will do the job

**Comment by RouxRC** [comment]
ah i thought so but I missed it, setting it up in prod now.
sorry about that :)
