### ISSUE TITLE
Handle keypress up/down in amendments

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory#142]
- Should handle the length of lines to know where to go when multiline
- Should allow to switch from on esubject to another, aligning vertically or to the maximum right if currently further
- This is going to be a happy mess to handle with the snake ordering added :)

**Comment by njoyard** [comment]
Actually I think snake ordering will make this easier, because we'll have to know where each amendment is displayed. Linking #131 here for reference :)

**Comment by njoyard** [comment]
There might still be an issue when in two column mode, I'll fix that tomorrow morning.

**Comment by njoyard** [comment]
All clear :)

**Comment by boogheta** [comment]
currently can't test it locally because of the weird crossdomains issues discussed on irc

**Comment by RouxRC** [comment]
Works great! including with the snake and multicolulm, really cool :)

Although I still see two minor fixes :)

The first one is not directly related to the keypress but rather to the multicolumn so i posted a dedicated issue #162 

The second one is that when moving up/down it would be best if the viz view would also scroll accordingly so that the selected amendment always remains visible, same way as in the articles view or when getting to an amendments page with a subject
