### ISSUE TITLE
How do we want to handle multiselection on Legend in mod2 & 2b

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory#143]
Currently we can multiselect for instance amendments from PS, only adopted ones
Although there's no indicator of a current selection on the legend, so one can hardly know why no amendment is selcted anymore in some cases
So we could either:
- add some visual markers on the legend when a selection is activated (problem seen: we already have a heavy interface, adding visual markers on a legend explaining visual markers can be quite confusing, hard to read and/or ugly) 
- never allow more than one selection (either subject, amendment, group, or status) (problem: lose on interface richness, advantage : simplify urls)

What do you think @njoyard @fmassot ?

**Comment by njoyard** [comment]
Maybe we could fade out unselected legend items ? That would add a visual clue without clobbering the UI more, I think.

**Comment by fmassot** [comment]
+1 for adding a visual clue, I see this kind of UI a lot in chart legends and it works quite well

**Comment by RouxRC** [comment]
sounds good to me!

**Comment by njoyard** [comment]
That leaves the question of multiple selection open...

**Comment by fmassot** [comment]
yep, the basic way to do it is with checkboxes but we can't do that :)

another way would be to have the same behaviour as a file manager : ctrl + left click enable multiple selection. imho this feature is not very important so this solution could be quite acceptable.

**Comment by RouxRC** [comment]
I think we could just drop the feature and simply have one kind of selection maximum

**Comment by fmassot** [comment]
+1 to drop it

**Comment by njoyard** [comment]
Agreed, closing :)
