### ISSUE TITLE
Refactor-v2 as master

### ISSUE THREAD

**Issue by fmassot** [regardscitoyens/the-law-factory#147]
refactor-v2 is now the real master branch, I suggest to rename the current master as v1 branch and rename refactor-v2 to master

**Comment by RouxRC** [comment]
i wanted to wait until all regressions were caught up, I guess we're nearly there now that snake is there, I've tried to list important things to finish in the refacto milestone

**Comment by fmassot** [comment]
but refactor-v2 is in production :)

**Comment by RouxRC** [comment]
shhhhh :)

**Comment by RouxRC** [comment]
now that we're close to switch to css-refacto i guess we can close this :)
