### ISSUE TITLE
height weirdly increased when navigating from the search bar  

### ISSUE THREAD

**Issue by fmassot** [regardscitoyens/the-law-factory#149]
Reproduced on latest chrome / firefox : 
 * go to https://www.lafabriquedelaloi.fr
 * type for example "mariage" in the search bar
 * you can already see that you can scroll down a little
 * then click on "Explorer les amendements"
 * and just scroll down !

**Comment by njoyard** [comment]
Would probably be fixed by fixing #152

**Comment by RouxRC** [comment]
i confirm it is still fixed with refacto :)
