### ISSUE TITLE
 ngRepeat:dupes error in js console

### ISSUE THREAD

**Issue by fmassot** [regardscitoyens/the-law-factory#150]
seen on page on refactor-v2 branch 
amendements.html?loi=pjl12-349&etape=02_1%C3%A8relecture_assemblee_hemicycle

**Comment by njoyard** [comment]
Oh, that means we have several amendments with the same id_api. Any idea how that would happen @RouxRC ? And if this is a normal situation ?

**Comment by njoyard** [comment]
Fixed by 87cd374
