### ISSUE TITLE
drop resize stuff

### ISSUE THREAD

**Issue by fmassot** [regardscitoyens/the-law-factory#152]
There are way too many calls of resize function in this app, we should drop that and just let the browser make this for us !
As @njoyard suggest, we can for example just use absolute positioning.

**Comment by RouxRC** [comment]
are we speaking only about amendments or everywhere ? :)

**Comment by njoyard** [comment]
Everywhere. Page layout is nearly the same in all modules.

**Comment by RouxRC** [comment]
go for it! just beware the probably numberous pieces of d3 that deal with sizes :)

**Comment by njoyard** [comment]
Progress can be followed on [my new-stylesheet branch](https://github.com/njoyard/the-law-factory/tree/new-stylesheet).

Note that in the end only the compiled CSS will be versioned and the branch will be rebased to separate commits into more targeted changes.

**Comment by RouxRC** [comment]
@fmassot I guess this is closable now with css-refacto, except if you meant also dropping the resize watches that are used to redraw the svgs?

**Comment by fmassot** [comment]
nope the refacto is just perfect !
