### ISSUE TITLE
Home page does not scroll anymore

### ISSUE THREAD

**Issue by njoyard** [regardscitoyens/the-law-factory#157]
Maybe related to https://github.com/regardscitoyens/the-law-factory/commit/88ee0f8d6c79cae6f15f44f06ac1d6b12465e827 ?

**Comment by boogheta** [comment]
The following seems to do the trick, but also seems to bring back the issue that 88ee0f8 was solving...
- remove the whole #home directive in the css
- add an "overflow: hidden" to the #wrapper one
- extract the nav-bar outside of the wrapper div in index.dev.html

**Comment by njoyard** [comment]
Maybe wait for my style refactor (#152) for that ?

**Comment by boogheta** [comment]
yep, makes sense

**Comment by njoyard** [comment]
Fixed by #164
