### ISSUE TITLE
[navettes] interface menu's style is broken in small screens since refacto

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory#158]
under a 1080pixels wide screen, the new style of the zoom element takes too much space and breaks the display of the years slector menu

I believe ensuring always at least 1024 screens is a minimurm requisite

**Comment by boogheta** [comment]
at least forcing max height of the menu maybe ?

**Comment by boogheta** [comment]
oups sorry, wrong window, it's already the case.
Although it remains a bit sad to get only the arrow on second line on small screens, maybe ensure always to have a word next to the arrow if that's possible? (not sure about that though, as it is a dedicated markup nbsp won't suffice and some kinf of css inline would probably be necessary)

**Comment by boogheta** [comment]
In any case, reducing the gap between the zoom text and slider would seem better

**Comment by njoyard** [comment]
Fixed in css-refactor : no line break is possible between text and caret (still possible inside text) and reduced space between zoom text and slider

**Comment by boogheta** [comment]
great, thanks!
