### ISSUE TITLE
[amendements] angular variables briefly appear in sidebar's title on slow browsers

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory#160]
Speaking about the content of the `<h4 id="text-title">`
Maybe set it as display:None in the css and .show() it only within the page's controller ?

**Comment by njoyard** [comment]
FYI, this is what the `ng-cloak` attribute is made for. I must have missed one :)

**Comment by boogheta** [comment]
ah great, I was wondering :)

Well there's one missing in the sidebar for sure, and I seem to have seen one regarding the legend as well earlier today
