### ISSUE TITLE
Homepage : Unable to scroll 

### ISSUE THREAD

**Issue by teymour** [regardscitoyens/the-law-factory#166]
The vertical scrollbar is disabled on the homepage.

Thus, only part of the highlighted texts are visible. The introduction to the different steps of the project is unaccessible at least on Debian (tested with firefox & chromium)

**Comment by njoyard** [comment]
This is fixed in https://github.com/regardscitoyens/the-law-factory/pull/165 btw

**Comment by teymour** [comment]
arf, sorry, i thought lafabriquedelaloi.fr was up to date.
