### ISSUE TITLE
Withdrawn amendments in senate are not handled correctly

### ISSUE THREAD

**Issue by njoyard** [regardscitoyens/the-law-factory#169]
Example:
http://www.senat.fr/amendements/commissions/2015-2016/325/Amdt_COM-117.html

In the law factory it shows as pending:
https://www.lafabriquedelaloi.fr/amendements.html?loi=pjl15-republique_numerique&etape=04_1%C3%A8relecture_senat_commission&amdt=COM-117

(probably a -parser issue, will check tonight)

**Comment by boogheta** [comment]
It comes from the fact we reload amendments from this page http://www.senat.fr/amendements/commissions/2015-2016/325/jeu_classe.html which does not include amendments once they've been retracted so they're not reupdated

We can simply fix it for now by changing the url to this one http://www.senat.fr/amendements/commissions/2015-2016/325/jeu_complet.html

In the long term we'll probably want to reload only amendments with missing status  soon to be discussed as we did for AN and will need to use the ordered version but until then, using the complete sets fixes the issue

**Comment by boogheta** [comment]
done for this time, should be fixed in lfdll soon
