### ISSUE TITLE
Unclick selected article from articles in amendments fails

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory#172]
When we reach amendments with an article already selected coming from the link button of the article in articles view, unselecting it results in everything being greyed instead of nothing being so

**Comment by njoyard** [comment]
I don't understand why it behaved incorrectly. Anyway, changed the way an article is selected from the URL and now it works... (on branch css-refactor)

**Comment by boogheta** [comment]
weird indeed, but well done!
