### ISSUE TITLE
[StepsBar] Resize could adjust steps name as before

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/the-law-factory#185]
When it was spying resizes it was also adjusting to the short names of each steps when necessary, we could have those names as conditional angular variables depending on a watch resize maybe?

**Comment by njoyard** [comment]
I think we can do that with CSS only, I'll give it a try.

**Comment by RouxRC** [comment]
reopening to poitn out two comments
- https://github.com/regardscitoyens/the-law-factory/commit/085e3dfee9e290ac2e9ba1a8ec304267ead433b0#commitcomment-17392382
- https://github.com/regardscitoyens/the-law-factory/commit/085e3dfee9e290ac2e9ba1a8ec304267ead433b0#commitcomment-17392371

**Comment by njoyard** [comment]
I just realized that, but we could have used CSS text-overflow instead of that. The downside being that it does not allow to control how text is shortened (so we would have had "Ass..." and "Comm...").

**Comment by RouxRC** [comment]
yeah I'd rather have more code but more explicit acronyms :)
