### ISSUE TITLE
Apparently broken parsing of tables

### ISSUE THREAD

**Issue by nathanncohen** [regardscitoyens/the-law-factory#195]
Merely reporting what was said before on IRC:

On the following page [1], let us click on the first article of Chapter 3, in its last version. This makes 'Article 29 (21)' appear on the right side of the screen, and one can see bullets containing only "

This seems to be related to the table at [2]

[1] https://www.lafabriquedelaloi.fr/articles.html?loi=pjl12-689
[2] http://www.assemblee-nationale.fr/14/ta-commission/r1109-a0.asp#P259_48071

**Comment by mdamien** [comment]
It only took us one year but La Fabrique has been updated and this is now fixed, thanks a lot for reporting it :+1:
