### ISSUE TITLE
Misleading link toward amendments

### ISSUE THREAD

**Issue by nathanncohen** [regardscitoyens/the-law-factory#196]
In the following page [1], let us click on the first article of Chapter 3, in its first version at the 'Senat'. On the (now updated) right panel appears a button entitled 'Explorer les amendements'.

This button, unfortunately, leads toward a page that does not mention article 21.

[1] https://www.lafabriquedelaloi.fr/articles.html?loi=pjl12-689

**Comment by RouxRC** [comment]
Looks like it's fixed now.
Although the diff which renames HATVP from "autorité de" to "autorité pour" is still real at this step, while there are [really no amendment corresponding](https://www.senat.fr/amendements/commissions/2012-2013/689/liste_discussion.html), so I can only guess this is a change made in a previous article in the text and forgotten at this article, but even though was systematised through the whole text by the commission before publishing it, one of those magical "Séance" diffs :)
