### ISSUE TITLE
Clicking on amendments doesn't work

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/the-law-factory#198]
Looks like the API link returns a 404 when clicking on an amendement: "https://www.nosdeputes.fr/api/document/Amendement/31036/json"

![image](https://user-images.githubusercontent.com/1469823/30020549-75855152-9164-11e7-84c1-a00a644020cb.png)

**Comment by boogheta** [comment]
API links should be bound to legislatures as well as elements to fix this, we need to check in ND's code how to fix this

**Comment by mdamien** [comment]
Fixed :tada:
