### ISSUE TITLE
Use short index values instead of full ones in step arguments

### ISSUE THREAD

**Issue by boogheta** [regardscitoyens/the-law-factory#222]
For instance: https://www.lafabriquedelaloi.fr/articles.html?loi=pjl11-288&article=1er&etape=06_constitutionnalit%C3%A9_conseilconstitutionnel_
would work with https://www.lafabriquedelaloi.fr/articles.html?loi=pjl11-288&article=1er&etape=06

(this will reduce the length of shared urls, and fix the potential urls breakage with accented steps

**Comment by mdamien** [comment]
Done here: https://github.com/regardscitoyens/the-law-factory/commit/839aceed94968106fd24d739eb7a882def5fd0f4
