### ISSUE TITLE
Accés aux amendement sur la LPR cassé pour le Sénat

### ISSUE THREAD

**Issue by mdamien** [regardscitoyens/the-law-factory#248]
Ex: https://www.lafabriquedelaloi.fr/amendements.html?loi=pjl19-722&etape=04_1erelecture_senat_commission

Surement lié à https://github.com/regardscitoyens/nosdeputes.fr/issues/148

EDIT: C'est lié à un amendement dont le groupe est "GEST"

EDIT 2: Réparé avec le hack précédent: https://github.com/regardscitoyens/the-law-factory-parser/commit/a186d56fa5f5932818874873282a182939ec7d79

**Comment by boogheta** [comment]
ca vient de l'historique des groupes pris au sénat dans l'opendata contrairement à l'AN où on le stocke en base. or dans l'opendata du sénat le nouveau groupe ecolo est GEST au lieu de EST chez nous d'ou la cassure, c réparé
