### ISSUE TITLE
make a better legend for amendements (mod2)

### ISSUE THREAD

**Issue by pierrejdlf** [regardscitoyens/the-law-factory#95]
- groupes politiques
- gouvernement
- status (adopté, rejeté, non voté)

justifié à gauche, passage à la ligne, espace, c'est pas clair.

**Comment by RouxRC** [comment]
Hey @pierrejdlf do you remember what you meant exactly here?

**Comment by pierrejdlf** [comment]
for example: http://www.lafabriquedelaloi.fr/amendements.html?loi=ppl13-007&etape=09_nouv.lect._assemblee_hemicycle&article=6

<img width="571" alt="capture d ecran 2016-01-17 a 12 41 55" src="https://cloud.githubusercontent.com/assets/1382064/12377268/b2a36510-bd17-11e5-9ad1-fdb4c9eaf3d2.png">

within the legend on the bottom, we should find a better layout to separate "actors" from "status"
aka:

> ***
> □ SRC  □ ECOLO  □ UDI  □ UMP □ Gouvernement
> ***
> □ Adopté  □ Rejeté  □ Non voté
> ***

or maybe 2 columns, one for actors, the other for th status ?

**Comment by RouxRC** [comment]
The problem is with most cases, you get too many groups if you include the government and it can't fit on only one line
That's why the government was rattached to the status line (and by coherence with the interventions where the firsty line is only the groups, and the second line the special people (gov, rapporteurs, auditionnés, ...)
So I don't see a better proposed solution so far :p

**Comment by fmassot** [comment]
I like the solution @pierrejdlf, I'm not sure to understand why we cannot fit the groups on one line. Is there more than 8 groups ? On very small screen, it can indeed be difficult to read but I found that the app is anyway not really readable on mobile phone for example.

**Comment by minut** [comment]
let's use columns !
and (well, maybe that's not a priority) make a mini-tata-viz !
<img width="292" alt="capture d ecran 2016-02-10 a 22 10 30" src="https://cloud.githubusercontent.com/assets/11555076/12961956/7255f524-d043-11e5-8647-fdfb6d25b9fe.png">

**Comment by pierrejdlf** [comment]
let's use columns !
and (well, maybe that's not a priority) make a mini-tata-viz !
<img width="292" alt="capture d ecran 2016-02-10 a 22 10 30" src="https://cloud.githubusercontent.com/assets/1382064/12962068/0867c510-d044-11e5-9659-0f8addb77b50.png">
