### ISSUE TITLE
CMP covering AN and Sénat stages?

### ISSUE THREAD

**Issue by kerneis** [regardscitoyens/the-law-factory#96]
My eye was catched by a surprisingly long CMP in:
http://www.lafabriquedelaloi.fr/lois.html?loi=pjl12-582

This seems to be caused by "Comission Mixte Paritaire" instead of "2ème lecture" being used for the last stage (unless I misunderstand what is going on).

**Comment by boogheta** [comment]
looks like it's fixed now
